::cisco::eem::event_register_none 

#
# This EEM tcl policy was generated by the EEM applet conversion
# utility at http://www.marcuscom.com/convert_applet/
# using the following applet:
#
# event manager applet hightalkers
# event none
# action 1.1 cli command "enable"
# action 1.2 info type routername
# action 1.5 cli command "show flow monitor FlowMonitor1 cache aggr ipv4 destin addr ipv4 source addr tran source-port tran destination-port ipv4 protocol application name timestamp sys-uptime first interface input sort counter bytes top 4 format table"
# action 1.6 mail server "10.44.108.95" to "carlton.patterson@skanska.co.uk" from "carlton.patterson@skanska.co.uk" subject "toptalkers: $_info_routername" body "TopTalker Script $_cli_result"
#

namespace import ::cisco::eem::*
namespace import ::cisco::lib::*

array set arr_einfo [event_reqinfo]


if [catch {cli_open} result] {
    error $result $errorInfo
} else {
    array set cli1 $result
}

if [catch {cli_exec $cli1(fd) "enable"} _cli_result] {
    error $_cli_result $errorInfo
}

array set _sinfo [sys_reqinfo_routername]
set _info_routername $_sinfo(routername)
if [catch {cli_exec $cli1(fd) "show flow monitor FlowMonitor1 cache aggr ipv4 destin addr ipv4 source addr tran source-port tran destination-port ipv4 protocol application name timestamp sys-uptime first interface input sort counter bytes top 4 format table"} _cli_result] {
    error $_cli_result $errorInfo
}


set mail_pre "Mailservername: 10.44.108.95\n"
append mail_pre "From: carlton.patterson@skanska.co.uk\n"
append mail_pre "To: carlton.patterson@skanska.co.uk\n"
append mail_pre "Cc: \n"
append mail_pre "Subject: toptalkers: $_info_routername\n\n"
append mail_pre "TopTalker Script $_cli_result\n\n"
set mail_msg [uplevel #0 [list subst -nobackslashes -nocommands $mail_pre]]
if [catch {smtp_send_email $mail_msg} result] {
    error $result $errorInfo
}


# Close open cli before exit.
catch {cli_close $cli1(fd) $cli1(tty_id)} result