---
core:
    num_workers: 100


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/Users/fholzapf/PycharmProjects/Ansible_NSO_pyATS/LLDP-Map/hosts.yaml"
        group_file: "/Users/fholzapf/PycharmProjects/Ansible_NSO_pyATS/LLDP-Map/groups.yaml"
        defaults_file: "/Users/fholzapf/PycharmProjects/Ansible_NSO_pyATS/LLDP-Map/defaults.yaml"
