# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

set dir [file dirname [info script]]
package ifneeded dns 1.3.1 [list source [file join $dir dns.tcl]]
package ifneeded ip 1.1.0 [list source [file join $dir ip.tcl]]
package ifneeded logger 0.6.2 [list source [file join $dir logger.tcl]]
