version: '3'
services:


# docker run -v /var/run/docker.sock:/var/run/docker.sock \
#            -v $(pwd)/jenkins_home:/var/jenkins_home \
#            -d \
#            --name jenkins \
#            -p 8000:8080 \
#            -p 50000:50000 \
#            -e JAVA_OPTS="-Djenkins.install.runSetupWizard=false" \
#            jenkins

  jenkins:
    build: jenkins/
    image: jenkins-server
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      - ./:/scripts

    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    env_file:
      - ./.envfile

  # webui:
  #   image: portainer/portainer
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #
  # checker1:
  #   build: .
  #   image: kecorbin/genie-neighbor-check
  #   restart: always
  #   # only supported for swarm
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #   volumes:
  #     - ./testbed.yaml:/scripts/testbed.yaml
  #   env_file:
  #     - ./.envfile
